matrix:
  include:
  - language: android
    sudo: false
    jdk: oraclejdk8
    os: linux
    dist: trusty
    before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
    cache:
      directories:
      - "$HOME/.yarn-cache"
      - "$HOME/.gradle/caches/"
      - "$HOME/.gradle/wrapper/"
    android:
      components:
      - tools
      - platform-tools
      - build-tools-23.0.3
      - android-23
      - build-tools-28.0.3
      - android-28
      - build-tools-29.0.2
      - android-29
      - extra-google-google_play_services
    install:
    - nvm install 10
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$PATH" 
    - cd example/
    - chmod +x travis_common.sh
    - ./travis_common.sh $TRAVIS_BRANCH
    - cd AwesomeProject
    - sed -i 's/minSdkVersion = 16/minSdkVersion = 17/g' android/build.gradle
    - sed -ie "s/23/28/g" node_modules/react-native-advertising-id/android/build.gradle
    script:
    - cd android
    - "./gradlew clean"
    - "./gradlew app:assembleRelease"
  - language: objective-c
    os: osx
    osx_image: xcode12
    node_js: 8
    cache:
      directories:
      - "$HOME/.yarn-cache"
    before_install:
    - nvm install 10
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$PATH" 
    - cd example/
    - chmod +x travis_common.sh
    - ./travis_common.sh $TRAVIS_BRANCH
    - cd AwesomeProject
    - cd ios
    - pod install
    script:
    - xcodebuild -workspace AwesomeProject.xcworkspace -configuration Debug
      -scheme AwesomeProject -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest" -derivedDataPath build/AwesomeProject | xcpretty
email:
    recipients:
      - junaid.akram@count.ly
    on_success: change